name = "taskcontract-api"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = true

[vars]
ENVIRONMENT = "production"
APP_URL = "https://taskcontract.app"

# Set with: wrangler secret put JWT_SECRET

[[d1_databases]]
binding = "DB"
database_name = "taskcontract"
database_id = "4e70cb3b-c5e8-4b75-ae23-b2f531699fd4"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "KV"
id = "e530d1aa3f3b420bbfa3c35d8baafeb4"

#[[r2_buckets]]
 # binding = "R2"
 # bucket_name = "taskcontract-attachments"

[triggers]
crons = ["15 * * * *"]

[observability]
enabled = true


